version: '3.7'

services:
  kong-migrations:
    image: "kong:latest"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    volumes:
        - "./kong.yml:/usr/local/kong/declarative/kong.yml"
        - "./log-mount:/usr/local/kong/logs"
        # - "./log-mount:/usr/local/kong//logs/error.log"
        # - "./log-mount:/usr/local/kong/logs/access.log"
    ports:
        - "8000:8000"
        - "8443:8443"
        - "8001:8001"
        - "127.0.0.1:9001:8001"
        - "127.0.0.1:8444:8444"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure