#services
GET http://127.0.0.1:8000/gists
Accept: application/json

GET http://127.0.0.1:8000/watch
Accept: application/json

# metrics
GET http://localhost:9001/status
Accept: application/json

GET http://localhost:9001/metrics
Accept: application/json